# Generated by Django 4.2.5 on 2023-09-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('one_hour_change', models.CharField(max_length=255)),
                ('twenty_four_hour_change', models.CharField(max_length=255)),
                ('seven_day_change', models.CharField(max_length=255)),
                ('market_cap', models.CharField(max_length=255)),
                ('volume_24h', models.CharField(max_length=255)),
                ('circulating_supply', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
